### PR TITLE
fix: fuse pass support checks pod preStop hook

### LINKED ISSUE #1278: [FEATURE] If `umount <mountpoint>` in preStop, do not serve fuse fd in csi
**What feature you'd like to add:**

**Why is this feature needed:**

### PR DESCRIPTION
**Pull request by zxh326**
disabe inject fuse envs or serve fuse fds when user config  umount via preStop hook

close https://github.com/juicedata/juicefs-csi-driver/issues/1278

### CODE REVIEW

File: pkg/controller/pod_driver.go [hunk 1]
```diff
@@ -1140,8 +1140,8 @@ func (p *PodDriver) newMountPod(ctx context.Context, pod *corev1.Pod, newPodName
 	if err := p.applyConfigPatch(ctx, newPod); err != nil {
 		log.Error(err, "apply config patch error, will ignore")
 	}
-	newSupportFusePass := util.SupportFusePass(newPod.Spec.Containers[0].Image)
-	if !util.SupportFusePass(newPod.Spec.Containers[0].Image) {
+	newSupportFusePass := util.PodSupportFusePass(newPod)
```
Comment (zwwhdls) [inline pkg/controller/pod_driver.go]: replace all `util.SupportFusePass` in this file

**Review by zwwhdls — APPROVED** [review]
check and replace https://github.com/juicedata/juicefs-csi-driver/blob/master/pkg/fuse/passfd/passfd.go#L105

**Review by zwwhdls — APPROVED** [review]
