### PR TITLE
discard local timeout, control the reconciler timeout by context

### LINKED ISSUE #403: [FEATURE] set env for timeout of system calls in csi
**What feature you'd like to add:**

**Why is this feature needed:**

### LINKED ISSUE #406: [BUG] Can't bind PVCs with Minio - context timeout
**What happened**:
I made a `StorageClass` that points to a `Secret` with `storage: minio`. I put in the credentials to a minio server that is accessible and the credentials are valid. I also tried with `envs: "{AWS_REGION: abcd }"`.
**What you expected to happen**:
JuiceFS could communicate with the minio server and bind the PVC.
**How to reproduce it (as minimally and precisely as possible)**:
Connect a minio bucket to JuiceFS.
**Anything else we need to know?**
Metadata is using CockroachDB, but that's working fine with a different data backend.
This is running with the arm modifications: https://juicefs.com/docs/csi/csi-in-arm64/#2-install-via-kubectl
When I run `telnet` within `juicefs-csi-controller-o/juicefs-plugin` I get a TCP connection to my minio data endpoint.

Sample Manifest:
```
apiVersion: v1
kind: Secret
metadata:
  name: juicefs-sc-secret-minio
  namespace: kube-system
type: Opaque
stringData:
  name: "minio"
  metaurl: "postgres://root@cockroachdb.cockroachdb:26257/juicefs?sslmode=disable"
  storage: "minio"
  bucket: "http://minio.minio:9000/juicefs"
  access-key: "juicefs"
  secret-key: "REDACTED"
  envs: "{AWS_REGION: oracle }"
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: juicefs-minio
provisioner: csi.juicefs.com
reclaimPolicy: Retain
volumeBindingMode: Immediate
parameters:
  csi.storage.k8s.io/node-publish-secret-name: juicefs-sc-secret-minio
  csi.storage.k8s.io/node-publish-secret-namespace: kube-system
  csi.storage.k8s.io/provisioner-secret-name: juicefs-sc-secret-minio
  csi.storage.k8s.io/provisioner-secret-namespace: kube-system
```

Output:
```
juicefs-csi-controller-0 csi-provisioner I0827 19:22:19.769071       1 controller.go:1317] provision "justin/web-pvc" class "juicefs-minio": started
juicefs-csi-controller-0 csi-provisioner I0827 19:22:19.769391       1 controller.go:573] CreateVolumeRequest {Name:pvc-bf81ebcc-0974-4ef0-a186-04f8733ffff4 CapacityRange:required_bytes:11258999068426240  VolumeCapabilities:[mount:<> access_mode:<mode:MULTI_NODE_MULTI_WRITER > ] Parameters:map[csi.storage.k8s.io/node-publish-secret-name:juicefs-sc-secret-minio csi.storage.k8s.io/node-publish-secret-namespace:kube-system csi.storage.k8s.io/provisioner-secret-name:juicefs-sc-secret-minio csi.storage.k8s.io/provisioner-secret-namespace:kube-system] Secrets:map[] VolumeContentSource:<nil> AccessibilityRequirements:<nil> XXX_NoUnkeyedLiteral:{} XXX_unrecognized:[] XXX_sizecache:0}
juicefs-csi-controller-0 csi-provisioner I0827 19:22:19.770594       1 event.go:282] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"justin", Name:"web-pvc", UID:"bf81ebcc-0974-4ef0-a186-04f8733ffff4", APIVersion:"v1", ResourceVersion:"44339926", FieldPath:""}): type: 'Normal' reason: 'Provisioning' External provisioner is provisioning volume for claim "justin/web-pvc"
juicefs-csi-controller-0 juicefs-plugin I0827 19:22:19.802942       7 controller.go:69] CreateVolume: Secrets contains keys [envs metaurl name secret-key storage access-key bucket env]
juicefs-csi-controller-0 csi-provisioner I0827 19:22:19.801408       1 connection.go:182] GRPC call: /csi.v1.Controller/CreateVolume
juicefs-csi-controller-0 csi-provisioner I0827 19:22:19.801448       1 connection.go:183] GRPC request: {"capacity_range":{"required_bytes":11258999068426240},"name":"pvc-bf81ebcc-0974-4ef0-a186-04f8733ffff4","secrets":"***stripped***","volume_capabilities":[{"AccessType":{"Mount":{}},"access_mode":{"mode":5}}]}
juicefs-csi-controller-0 juicefs-plugin I0827 19:22:19.803466       7 juicefs.go:626] ceFormat cmd: [/usr/local/bin/juicefs format --storage=minio --bucket=https://minio.minio:9000/juicefs --access-key=juicefs --secret-key=${secretkey} ${metaurl} minio]
juicefs-csi-controller-0 liveness-probe I0827 19:22:24.634134       1 connection.go:153] Connecting to unix:///csi/csi.sock
juicefs-csi-controller-0 juicefs-plugin I0827 19:22:24.804764       7 juicefs.go:647] Format output is 
juicefs-csi-controller-0 csi-provisioner I0827 19:22:24.805714       1 connection.go:185] GRPC response: {}
juicefs-csi-controller-0 juicefs-plugin E0827 19:22:24.804904       7 driver.go:83] GRPC error: rpc error: code = Internal desc = Could not createVol in juicefs: rpc error: code = Internal desc = rpc error: code = Internal desc = context timeout
juicefs-csi-controller-0 csi-provisioner I0827 19:22:24.805881       1 connection.go:186] GRPC error: rpc error: code = Internal desc = Could not createVol in juicefs: rpc error: code = Internal desc = rpc error: code = Internal desc = context timeout
juicefs-csi-controller-0 csi-provisioner I0827 19:22:24.805955       1 controller.go:645] CreateVolume failed, supports topology = false, node selected false => may reschedule = false => state = Finished: rpc error: code = Internal desc = Could not createVol in juicefs: rpc error: code = Internal desc = rpc error: code = Internal desc = context timeout
juicefs-csi-controller-0 csi-provisioner I0827 19:22:24.806115       1 controller.go:1084] Final error received, removing PVC bf81ebcc-0974-4ef0-a186-04f8733ffff4 from claims in progress
juicefs-csi-controller-0 csi-provisioner W0827 19:22:24.807358       1 controller.go:943] Retrying syncing claim "bf81ebcc-0974-4ef0-a186-04f8733ffff4", failure 7
juicefs-csi-controller-0 csi-provisioner E0827 19:22:24.807458       1 controller.go:966] error syncing claim "bf81ebcc-0974-4ef0-a186-04f8733ffff4": failed to provision volume with StorageClass "juicefs-minio": rpc error: code = Internal desc = Could not createVol in juicefs: rpc error: code = Internal desc = rpc error: code = Internal desc = context timeout
juicefs-csi-controller-0 csi-provisioner I0827 19:22:24.806325       1 event.go:282] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"justin", Name:"web-pvc", UID:"bf81ebcc-0974-4ef0-a186-04f8733ffff4", APIVersion:"v1", ResourceVersion:"44339926", FieldPath:""}): type: 'Warning' reason: 'ProvisioningFailed' failed to provision volume with StorageClass "juicefs-minio": rpc error: code = Internal desc = Could not createVol in juicefs: rpc error: code = Internal desc = rpc error: code = Internal desc = context timeout
juicefs-csi-controller-0 liveness-probe I0827 19:22:34.635071       1 connection.go:153] Connecting to unix:///csi/csi.sock
juicefs-csi-controller-0 liveness-probe I0827 19:22:44.633771       1 connection.go:153] Connecting to unix:///csi/csi.sock
juicefs-csi-controller-0 liveness-probe I0827 19:22:54.634751       1 connection.go:153] Connecting to unix:///csi/csi.sock
```

**Environment**:
- JuiceFS CSI Driver version (which image tag did your CSI Driver use):  The ones listed here: https://juicefs.com/docs/csi/csi-in-arm64/#2-install-via-kubectl
- Kubernetes version (e.g. `kubectl version`): v1.24.2+k3s2
- Object storage (cloud provider and region): minio running in same K3S cluster behind a `Service`
- Metadata engine info (version, cloud provider managed or self maintained):
- Network connectivity (JuiceFS to metadata engine, JuiceFS to object storage): All within k3s. CockroachDB metadata, minio data.
- Others:

### PR DESCRIPTION
**Pull request by Hexilee**
There are too many local settings to control the timeout of the whole calling chain, which is unconfigurable and may cause dead goroutine in `kubelet` or controller-runtime.

So, we should only control the timeout of the top context, then we need only to set the global context timeout of controller-runtime (and the `kubelet` sets context timeout by self).

close #403 and #406

### CODE REVIEW

File: pkg/juicefs/juicefs.go [hunk 1]
```diff
@@ -379,7 +378,7 @@ func (j *juicefs) JfsUnmount(volumeId, mountPath string) error {
 				delete(j.CacheDirMaps, uniqueId)
 
 				klog.V(5).Infof("Cleanup cache of volume %s in node %s", uniqueId, config.NodeName)
-				go j.processMount.CleanCache(uuid, uniqueId, cacheDirs)
+				go j.processMount.CleanCache(ctx, uuid, uniqueId, cacheDirs)
```
Comment (zwwhdls) [inline pkg/juicefs/juicefs.go]: cleanCache may take long time, do not set timeout for it.

File: pkg/juicefs/mount/pod_mount.go [hunk 2]
```diff
@@ -318,22 +318,25 @@ func (p *PodMount) createOrAddRef(jfsSetting *jfsConfig.JfsSetting) (podName str
...
+		return podName, p.AddRefOfMount(ctx, jfsSetting.TargetPath, podName)
 	}
 	return podName, status.Errorf(codes.Internal, "Mount %v failed: mount pod %s has been deleting for 1 min", jfsSetting.VolumeId, podName)
 }
 
-func (p *PodMount) waitUtilMountReady(jfsSetting *jfsConfig.JfsSetting, podName string) error {
+func (p *PodMount) waitUtilMountReady(ctx context.Context, jfsSetting *jfsConfig.JfsSetting, podName string) error {
 	// Wait until the mount point is ready
-	for i := 0; i < 60; i++ {
+	for {
```
Comment (zwwhdls) [inline pkg/juicefs/mount/pod_mount.go:334]: set timeout for check mountpoint

**Review by zwwhdls — CHANGES_REQUESTED** [review]

File: pkg/juicefs/juicefs.go (hunk 1 above)
Comment (Hexilee) [reply pkg/juicefs/juicefs.go]: Fixed

File: pkg/juicefs/mount/pod_mount.go (hunk 2 above)
Comment (Hexilee) [reply pkg/juicefs/mount/pod_mount.go:334]: Fixed

File: pkg/util/util.go [hunk 3]
```diff
@@ -39,6 +33,11 @@ import (
 	"strconv"
 	"strings"
 	"time"
+
+	"github.com/juicedata/juicefs-csi-driver/pkg/config"
```
Comment (davies) [inline pkg/util/util.go:37]: Can you move these formatting and adding Context into another PR, without any behavior changes, so we can have a small PR and focus on the actual changes?

Comment (Hexilee) [reply pkg/util/util.go:37]: Yes, formatting can be moved to another PR, but adding Context is the main change actually. (I supplement more explanation in the description)

**Review by zwwhdls — APPROVED** [review]

File: pkg/util/util.go (hunk 3 above)
Comment (davies) [reply pkg/util/util.go:37]: We can pass context.TODO around without actually using it, then we can get rid most of changes out of this  PR, and focus on the actual changed behaviors. Otherwise we may miss some important changes.

Comment (Hexilee) [reply pkg/util/util.go:37]: Ok, I'm going to create a new PR to pass context around.

File: pkg/juicefs/mount/pod_mount.go [hunk 4]
```diff
@@ -358,13 +363,16 @@ func (p *PodMount) waitUtilMountReady(ctx context.Context, jfsSetting *jfsConfig
 
 func (p *PodMount) waitUtilJobCompleted(ctx context.Context, jobName string) error {
 	// Wait until the job is completed
-	for i := 0; i < 120; i++ {
+	for {
```
Comment (zwwhdls) [inline pkg/juicefs/mount/pod_mount.go:371]: Add the sub-timeout here? Avoid invalid waits.

File: pkg/juicefs/mount/pod_mount.go [hunk 5]
```diff
@@ -287,7 +287,7 @@ func (p *PodMount) createOrAddRef(ctx context.Context, jfsSetting *jfsConfig.Jfs
 	r := builder.NewBuilder(jfsSetting)
 	secret := r.NewSecret()
 	key := util.GetReferenceKey(jfsSetting.TargetPath)
-	for i := 0; i < 120; i++ {
+	for {
```
Comment (zwwhdls) [inline pkg/juicefs/mount/pod_mount.go:293]: Add the sub-timeout here. Avoid invalid waits.

File: pkg/juicefs/mount/pod_mount.go (hunk 4 above)
Comment (Hexilee) [reply pkg/juicefs/mount/pod_mount.go:371]: Done

File: pkg/juicefs/mount/pod_mount.go (hunk 5 above)
Comment (Hexilee) [reply pkg/juicefs/mount/pod_mount.go:293]: Done

File: pkg/juicefs/mount/process_mount.go [hunk 6]
```diff
@@ -108,13 +108,15 @@ func (p *ProcessMount) JDeleteVolume(ctx context.Context, jfsSetting *jfsConfig.
...
 	var existed bool
 
-	if _, err := util.DoWithinTime(ctx, defaultCheckTimeout, nil, func() (err error) {
+	if err := util.DoWithTimeout(ctx, defaultCheckTimeout, func() (err error) {
 		existed, err = k8sMount.PathExists(volPath)
 		return err
 	}); err != nil {
 		return fmt.Errorf("could not check volume path %q exists: %v", volPath, err)
 	} else if existed {
-		stdoutStderr, err := p.RmrDir(ctx, volPath, jfsSetting.IsCe)
```
Comment (davies) [inline pkg/juicefs/mount/process_mount.go]: This may take a long time to delete a volume with many files, remove this timeout.

File: pkg/juicefs/juicefs.go [hunk 7]
```diff
@@ -544,17 +542,15 @@ func (j *juicefs) AuthFs(ctx context.Context, secrets map[string]string, setting
 		return cmd, nil
 	}
 
-	authCmd := j.Exec.CommandContext(ctx, config.CliPath, args...)
+	cmdCtx, cmdCancel := context.WithTimeout(ctx, 5*defaultCheckTimeout)
```
Comment (zwwhdls) [inline pkg/juicefs/juicefs.go]: 10s may not enough, set 15s ?

File: pkg/juicefs/juicefs.go [hunk 8]
```diff
@@ -544,17 +542,15 @@ func (j *juicefs) AuthFs(ctx context.Context, secrets map[string]string, setting
...
 	for key, val := range setting.Envs {
 		envs = append(envs, fmt.Sprintf("%s=%s", key, val))
 	}
 	authCmd.SetEnv(envs)
-	var res []byte
-	_, err := util.DoWithinTime(ctx, 5*time.Second, nil, func() (err error) {
-		res, err = authCmd.CombinedOutput()
-		return
-	})
+	res, err := authCmd.CombinedOutput()
```
Comment (zwwhdls) [inline pkg/juicefs/juicefs.go:553]: If error is timeout, complete the return info? Like: "juicefs auth timeout..."

File: pkg/juicefs/juicefs.go [hunk 9]
```diff
@@ -679,7 +675,9 @@ func (j *juicefs) ceFormat(ctx context.Context, secrets map[string]string, noUpd
 		return cmd, nil
 	}
 
-	formatCmd := j.Exec.CommandContext(ctx, config.CeCliPath, args...)
+	cmdCtx, cmdCancel := context.WithTimeout(ctx, 5*defaultCheckTimeout)
```
Comment (zwwhdls) [inline pkg/juicefs/juicefs.go]: ditto

File: pkg/juicefs/juicefs.go [hunk 10]
```diff
@@ -688,11 +686,7 @@ func (j *juicefs) ceFormat(ctx context.Context, secrets map[string]string, noUpd
 		envs = append(envs, "JFS_NO_CHECK_OBJECT_STORAGE=1")
 	}
 	formatCmd.SetEnv(envs)
-	var res []byte
-	_, err := util.DoWithinTime(ctx, 5*time.Second, nil, func() (err error) {
-		res, err = formatCmd.CombinedOutput()
-		return
-	})
+	res, err := formatCmd.CombinedOutput()
```
Comment (zwwhdls) [inline pkg/juicefs/juicefs.go:693]: ditto

File: pkg/juicefs/mount/process_mount.go (hunk 6 above)
Comment (Hexilee) [reply pkg/juicefs/mount/process_mount.go]: Removed

File: pkg/juicefs/juicefs.go (hunk 7 above)
Comment (Hexilee) [reply pkg/juicefs/juicefs.go]: Well, set to `8 * defaultCheckTimeout`

File: pkg/juicefs/juicefs.go (hunk 8 above)
Comment (Hexilee) [reply pkg/juicefs/juicefs.go:553]: Done

File: pkg/juicefs/juicefs.go (hunk 9 above)
Comment (Hexilee) [reply pkg/juicefs/juicefs.go]: Done

File: pkg/juicefs/juicefs.go (hunk 10 above)
Comment (Hexilee) [reply pkg/juicefs/juicefs.go:693]: Done

**Review by davies — APPROVED** [review]
