### PR TITLE
fix resource err pod cannot be deleted

### LINKED ISSUE #438: [BUG] mount pod is resource error but can not be terminated
**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**

**Environment**:
- JuiceFS CSI Driver version (which image tag did your CSI Driver use):
- Kubernetes version (e.g. `kubectl version`):
- Object storage (cloud provider and region):
- Metadata engine info (version, cloud provider managed or self maintained):
- Network connectivity (JuiceFS to metadata engine, JuiceFS to object storage):
- Others:

### PR DESCRIPTION
**Pull request by zwwhdls**
fix https://github.com/juicedata/juicefs-csi-driver/issues/438

### CODE REVIEW

File: pkg/controller/pod_driver.go [hunk 1]
```diff
@@ -249,18 +255,18 @@ func (p *PodDriver) podDeletedHandler(ctx context.Context, pod *corev1.Pod) erro
...
-
 	// remove finalizer of pod
 	if err := util.RemoveFinalizer(ctx, p.Client, pod, config.Finalizer); err != nil {
 		klog.Errorf("remove pod finalizer err:%v", err)
 		return err
 	}
 
+	// pod with resource error
+	if util.IsPodResourceError(pod) {
+		klog.V(5).Infof("The pod is PodResourceError, podDeletedHandler skip delete the pod:%s", pod.Name)
```
Comment (Hexilee) [inline pkg/controller/pod_driver.go]: Shall we change this log? As this pod is deleted.

**Review by Hexilee — APPROVED** [review]
Rest LGTM
