### PR TITLE
fix format option

### LINKED ISSUE #312: [FEATURE] Can't use format parameter which is new in JuiceFS
**What feature you'd like to add:**

**Why is this feature needed:**

### PR DESCRIPTION
**Pull request by zwwhdls**
fix https://github.com/juicedata/juicefs-csi-driver/issues/312

### CODE REVIEW

File: pkg/juicefs/juicefs.go [hunk 1]
```diff
@@ -489,6 +496,13 @@ func (j *juicefs) ceFormat(secrets map[string]string, noUpdate bool, setting *co
 	cmdArgs = append(cmdArgs, "${metaurl}", secrets["name"])
 	args = append(args, secrets["metaurl"], secrets["name"])
 
+	if setting.FormatOptions != "" {
+		formatOptions := strings.Split(setting.FormatOptions, ",")
+		for _, o := range formatOptions {
+			args = append(args, fmt.Sprintf("--%s", o))
```
Comment (davies) [inline pkg/juicefs/juicefs.go]: remove space in o, ignore it if it's empty
