### PR TITLE
fix: volume subpath is created with 755 permission

### LINKED ISSUE #1393: [BUG] volume subpath is created with 755 permission
**What happened**:

In v0.29.0, `enableControllerSetQuota` is set to true by default. This means `juicefs set quota --create` is executed on the juicefs-csi-controller.

This command creates a subdirectory within the volume. but, the permission might be 755 not 777.

As a result, the application can’t write to our juicefs unless root.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**

**Environment**:
- JuiceFS CSI Driver version (which image tag did your CSI Driver use):
- Kubernetes version (e.g. `kubectl version`):
- Object storage (cloud provider and region):
- Metadata engine info (version, cloud provider managed or self maintained):
- Network connectivity (JuiceFS to metadata engine, JuiceFS to object storage):
- Others:

### PR DESCRIPTION
**Pull request by kyungwan-nam**
fix https://github.com/juicedata/juicefs-csi-driver/issues/1393

### CODE REVIEW

File: pkg/juicefs/juicefs.go [hunk 1]
```diff
@@ -649,7 +649,8 @@ func (j *juicefs) SetQuota(ctx context.Context, secrets map[string]string, jfsSe
 		if err != nil {
 			return errors.Wrap(err, authRes)
 		}
-		quotaCmd := j.Exec.CommandContext(cmdCtx, config.CliPath, args...)
+		cmdStr := fmt.Sprintf("umask 000; %s %s", config.CliPath, strings.Join(args, " "))
+		quotaCmd := j.Exec.CommandContext(cmdCtx, "/bin/bash", "-c", cmdStr)
```
Comment (zxh326) [inline pkg/juicefs/juicefs.go]:
```suggestion
		quotaCmd := j.Exec.CommandContext(cmdCtx, "sh", "-c", cmdStr)
```

**Review by zxh326 — COMMENTED** [review]
LGTM

cc @zwwhdls
