### PR TITLE
fix config generate in upgrade

### LINKED ISSUE #1257: [BUG] csi 升级配置修改兼容性问题
**What happened**:
旧版本 csi 生成的 pod 没有做任何配置修改，仍然会被升级
原因是 旧版的 csi 生成的 mount pod 的配置是 csi 拼成的（有一些信息拿不到），没有记录在 secret 里，然后升级的时候拿拼凑出来的配置和现有的做对比，主要是拿配置 setting 算出一个 hash 做对比，所以会不准。现在新的版本里是把 setting 存在 secret 里，这样每次都是拿上一次生成的配置。
拿旧版本生成的 pod 前两次升级会有这个问题，第三次就固定了
**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**

**Environment**:
- JuiceFS CSI Driver version (which image tag did your CSI Driver use):
- Kubernetes version (e.g. `kubectl version`):
- Object storage (cloud provider and region):
- Metadata engine info (version, cloud provider managed or self maintained):
- Network connectivity (JuiceFS to metadata engine, JuiceFS to object storage):
- Others:

### PR DESCRIPTION
**Pull request by zwwhdls**
fix https://github.com/juicedata/juicefs-csi-driver/issues/1257

1. refactor: parse settings in one function
2. regenerate settings: if pv/pvc/secret can be fetched, use parseSetting as `publishVolume` does.

### CODE REVIEW

File: pkg/config/command.go [hunk 1]
```diff
@@ -185,3 +191,42 @@ func GenFormatCmd(secrets map[string]string, noUpdate bool, setting *JfsSetting)
 
 	return
 }
+
+// GenJfsVolUUID get UUID from result of `juicefs status <volumeName>`
+func GenJfsVolUUID(ctx context.Context, s *JfsSetting) (string, error) {
```
Comment (zxh326) [inline pkg/config/command.go]:
```suggestion
func GetJfsVolUUID(ctx context.Context, s *JfsSetting) (string, error) {
```

It looks like `get` rather than `gen`?

**Review by zxh326 — APPROVED** [review]
