### PR TITLE
fix mysql connect parse

### LINKED ISSUE #170: When mysql is the metadata storage engine, error: "Syntax error: "(" unexpected"
### version：
`juicedata/juicefs-csi-driver:     v0.10.5`
### detail:
```
pod status：
juicefs-<nodeName>-<pvName>     CrashLoopBackOff

incorrect command：
/bin/mount.juicefs mysql://root:123456@(10.99.100.166:3306)/juicefs /jfs/<pvName>
err message:
Syntax error: "(" unexpected

correct command：
/bin/mount.juicefs mysql://root:123456@\(10.99.100.166:3306\)/juicefs /jfs/<pvName>
success
```

### PR DESCRIPTION
**Pull request by zwwhdls**
fix https://github.com/juicedata/juicefs-csi-driver/issues/170

### CODE REVIEW

File: pkg/juicefs/mount/pod.go [hunk 1]
```diff
@@ -248,3 +249,13 @@ func getCacheDirVolumes(cmd string) ([]corev1.Volume, []corev1.VolumeMount) {
 
 	return cacheVolumes, cacheVolumeMounts
 }
+
+func transformCmd(cmd string) string {
```
Comment (davies) [inline pkg/juicefs/mount/pod.go]: nit: escapeForShell or quoteForShell ?

**Review by davies — APPROVED** [review]
