### PR TITLE
fix set quota

### LINKED ISSUE #1260: [BUG] not return quota timeout error in ControllerExpand api
**What happened**:

In the `ControllerExpand` API, if a quota setting timeout error, we return success and running in background

https://github.com/juicedata/juicefs-csi-driver/blob/2814fcaee5c7ebfe1f418353e566625d991b576e/pkg/juicefs/juicefs.go#L659-L662

If the quota continues to fail in the background, there will be no opportunity to retry, and we need to fix this behavior.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**

**Environment**:
- JuiceFS CSI Driver version (which image tag did your CSI Driver use): v0.23.1~
- Kubernetes version (e.g. `kubectl version`):
- Object storage (cloud provider and region):
- Metadata engine info (version, cloud provider managed or self maintained):
- Network connectivity (JuiceFS to metadata engine, JuiceFS to object storage):
- Others:

### PR DESCRIPTION
**Pull request by zxh326**
fix #1260 

- Remove the logic that runs in the background upon `setQuota` timeout in the community version.

  after https://github.com/juicedata/juicefs-csi-driver/pull/1223, `NodePublish api` always running setQuota in background
  
  when expanding PVCs, timeouts must return errors to permit retries.

- Adjust csi-resizer timeout to 20s.

### CODE REVIEW

File: pkg/juicefs/juicefs.go [hunk 1]
```diff
@@ -644,25 +644,14 @@ func (j *juicefs) SetQuota(ctx context.Context, secrets map[string]string, jfsSe
 		return wrapSetQuotaErr(string(res), err)
 	}
 
-	done := make(chan error, 1)
-	go func() {
-		// ce cli will block until quota is set
```
Comment (zxh326) [inline pkg/juicefs/juicefs.go:649]: If the meta is abnormal, it won't block here

**Review by zwwhdls — APPROVED** [review]
Make sure `timeout` in resizer is also added in chart
