### PR TITLE
fix get uuid error when database not format

### LINKED ISSUE #598: [BUG] when param "juicefs/clean-cache" is setting in storageclass，juicefs-csi-node output "juicefs status error: exit status 1"
**What happened**:
when param "juicefs/clean-cache" is setting in storageclass，juicefs-csi-node output "juicefs status error: exit status 1"

### **juicefs-csi-node log**
I0313 03:29:34.375180       6 node.go:78] NodePublishVolume: volume_id is pvc-a28db406-4c70-4c46-8a0b-2968510081d0
I0313 03:29:34.375214       6 node.go:89] NodePublishVolume: volume_capability is mount:<fs_type:"juicefs" mount_flags:"backup-meta=28800" > access_mode:<mode:MULTI_NODE_MULTI_WRITER > 
I0313 03:29:34.375256       6 node.go:95] NodePublishVolume: creating dir /var/lib/kubelet/pods/8401c4cf-dadc-48b9-867e-436463f77408/volumes/kubernetes.io~csi/pvc-a28db406-4c70-4c46-8a0b-2968510081d0/mount
I0313 03:29:34.375281       6 node.go:110] NodePublishVolume: volume context: map[csi.storage.k8s.io/node-publish-secret-name:juicefs-secret csi.storage.k8s.io/node-publish-secret-namespace:kube-system csi.storage.k8s.io/provisioner-secret-name:juicefs-secret csi.storage.k8s.io/provisioner-secret-namespace:kube-system juicefs/clean-cache:true juicefs/mount-cpu-limit:4000m juicefs/mount-cpu-request:100m juicefs/mount-delete-delay:1m juicefs/mount-image:juicedata/mount:v1.0.3-4.8.3 juicefs/mount-memory-limit:4Gi juicefs/mount-memory-request:100Mi pathPattern:${.PVC.namespace}-${.PVC.name} subPath:default-juicefs-pvc]
I0313 03:29:34.375308       6 node.go:120] NodePublishVolume: mounting juicefs with secret [bucket trash-days secret-key envs metaurl name format-options storage access-key], options [backup-meta=28800]
I0313 03:29:34.375526       6 juicefs.go:733] ceFormat cmd: [/usr/local/bin/juicefs format --storage=minio --bucket=http://192.168.x.xxx:9000/juicefs --access-key=admin --secret-key=${secretkey} ${metaurl} juicefs-test --trash-days=0 --block-size=4096]
I0313 03:29:34.454031       6 juicefs.go:354] juicefs status error: exit status 1, output: '2023/03/13 03:29:34.449210 juicefs[21250] <INFO>: Meta address: redis://:****@192.168.x.xxx:6379/1 [interface.go:402]
2023/03/13 03:29:34.450346 juicefs[21250] <WARNING>: AOF is not enabled, you may lose data if Redis is not shutdown properly. [info.go:83]
2023/03/13 03:29:34.450489 juicefs[21250] <INFO>: Ping redis: 69.611μs [redis.go:2888]
2023/03/13 03:29:34.450646 juicefs[21250] <FATAL>: load setting: database is not formatted, please run `juicefs format ...` first [status.go:71]

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
### **param "juicefs/clean-cache" is setting in storageclass**
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: juicefs-sc
provisioner: csi.juicefs.com
parameters:
  csi.storage.k8s.io/provisioner-secret-name: juicefs-secret
  csi.storage.k8s.io/provisioner-secret-namespace: kube-system
  csi.storage.k8s.io/node-publish-secret-name: juicefs-secret
  csi.storage.k8s.io/node-publish-secret-namespace: kube-system
  juicefs/mount-delete-delay: 1m
  juicefs/clean-cache: "true"
  juicefs/mount-image: juicedata/mount:v1.0.3-4.8.3
  juicefs/mount-cpu-limit: 4000m
  juicefs/mount-memory-limit: 4Gi
  juicefs/mount-cpu-request: 100m
  juicefs/mount-memory-request: 100Mi
  pathPattern: "${.PVC.namespace}-${.PVC.name}"
mountOptions:
  - backup-meta=28800
volumeBindingMode: Immediate
reclaimPolicy: Delete
**Anything else we need to know?**

**Environment**:
- JuiceFS CSI Driver version (which image tag did your CSI Driver use):juicefs-csi-driver:v0.18.1
- Kubernetes version (e.g. `kubectl version`):v1.19.3
- Object storage (cloud provider and region):minio
- Metadata engine info (version, cloud provider managed or self maintained):redis
- Network connectivity (JuiceFS to metadata engine, JuiceFS to object storage):
- Others:

### PR DESCRIPTION
**Pull request by zwwhdls**
fix https://github.com/juicedata/juicefs-csi-driver/issues/598

### CODE REVIEW

File: pkg/juicefs/mount/pod_mount.go [hunk 1]
```diff
@@ -436,6 +453,45 @@ func (p *PodMount) AddRefOfMount(ctx context.Context, target string, podName str
...
+// GetJfsVolUUID get UUID from result of `juicefs status <volumeName>`
+func (p *PodMount) GetJfsVolUUID(ctx context.Context, name string) (string, error) {
+	cmdCtx, cmdCancel := context.WithTimeout(ctx, 8*defaultCheckTimeout)
+	defer cmdCancel()
+	stdout, err := p.Exec.CommandContext(cmdCtx, jfsConfig.CeCliPath, "status", name).CombinedOutput()
+	if err != nil {
+		re := string(stdout)
+		if strings.Contains(re, "database is not formatted") {
+			klog.V(6).Infof("juicefs %s not formatted.", name)
+			return "", nil
```
Comment (Hexilee) [inline pkg/juicefs/mount/pod_mount.go]: Should it also be an unexpected case? As we already called `waitUtilMountReady` before calling `GetJfsVolUUID`.

Comment (zwwhdls) [reply pkg/juicefs/mount/pod_mount.go]: done

**Review by Hexilee — APPROVED** [review]
LGTM
