### PR TITLE
fix apply config in `STORAGE_CLASS_SHARE_MOUNT` mode

### LINKED ISSUE #1065: [BUG] restart mountpod cannot apply config in `STORAGE_CLASS_SHARE_MOUNT` mode
because it is impossible to obtain the mountpod pv

### PR DESCRIPTION
**Pull request by zxh326**
fix: https://github.com/juicedata/juicefs-csi-driver/issues/1065

### CODE REVIEW

File: pkg/config/setting.go [hunk 1]
```diff
@@ -757,3 +769,17 @@ func IsCEMountPod(pod *corev1.Pod) bool {
 	}
 	return false
 }
+
+func getPVNameFromTarget(target string) string {
```
Comment (zwwhdls) [inline pkg/config/setting.go:774]: Add unit test for this function

**Review by zwwhdls — APPROVED** [review]
