### PR TITLE
Smooth upgrade mount pod

### LINKED ISSUE #1111: [csi 平滑升级] 平滑升级问题和改进
**What happened**:

**What you expected to happen**:
1、dashboard没有记录平滑升级相关事件
image
2、 csi  权限没有加，平滑升级导致业务Bad file number

3、dashboard 平滑升级建议显示一下进行中和成功、失败

4、平滑升级后 宿主机df卡住，老的mount pod 挂载点卡住的。 而且应用pod内的挂载点也卡住
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**

**Environment**:
- JuiceFS CSI Driver version (which image tag did your CSI Driver use):
- Kubernetes version (e.g. `kubectl version`):
- Object storage (cloud provider and region):
- Metadata engine info (version, cloud provider managed or self maintained):
- Network connectivity (JuiceFS to metadata engine, JuiceFS to object storage):
- Others:

### LINKED ISSUE #1123: [BUG]  csi平滑升级，对象存储网络不稳定情况下，多次平滑升级出现挂载点卡住
**What happened**:
1、模拟对象存储网络异常
2、重启csi pod (不清楚是否有影响)
3、恢复对象存储网络
4、恢复时进行多次平滑升级
5、挂载点卡住，df卡住
6、csi pod也卡住（已解决）
**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**

**Environment**:
- JuiceFS CSI Driver version (which image tag did your CSI Driver use):
- Kubernetes version (e.g. `kubectl version`):
- Object storage (cloud provider and region):
- Metadata engine info (version, cloud provider managed or self maintained):
- Network connectivity (JuiceFS to metadata engine, JuiceFS to object storage):
- Others:

### PR DESCRIPTION
**Pull request by zwwhdls**
1. trigger upgrade in dashboard
2. smooth upgrade mount pod in csi

close https://github.com/juicedata/juicefs-csi-driver/issues/1111
close https://github.com/juicedata/juicefs-csi-driver/issues/1123

### CODE REVIEW

File: pkg/fuse/grace.go [hunk 1]
```diff
@@ -0,0 +1,364 @@
...
+func downloadBinary(ctx context.Context, client *k8s.K8sClient, pod *corev1.Pod, canaryPod string) error {
+	// download binary
+	ce := util.ContainSubString(pod.Spec.Containers[0].Command, "format")
+	if ce {
+		stdout, stderr, err := client.ExecuteInContainer(
+			ctx,
+			canaryPod,
+			config.Namespace,
+			"canary",
+			[]string{"sh", "-c", "cp /usr/local/bin/juicefs /tmp/juicefs"},
```
Comment (zxh326) [inline pkg/fuse/grace.go]: make tmp binary file name to unique to avoid conflict

Comment (zxh326) [reply pkg/fuse/grace.go]: also need clean tmp file

File: pkg/fuse/grace.go [hunk 2]
```diff
@@ -0,0 +1,364 @@
...
+		}
+		return nil
+	}
+
+	stdout, stderr, err := client.ExecuteInContainer(
+		ctx,
+		pod.Name,
+		pod.Namespace,
+		config.MountContainerName,
+		[]string{"sh", "-c", "rm -rf /usr/bin/juicefs && cp /tmp/juicefs /usr/bin/juicefs  && rm -rf /usr/local/juicefs/mount/jfsmount && cp /tmp/jfsmount /usr/local/juicefs/mount/jfsmount"},
```
Comment (zxh326) [inline pkg/fuse/grace.go]: can we use `mv` instead of `cp`?

File: pkg/fuse/grace.go [hunk 3]
```diff
@@ -0,0 +1,364 @@
...
+
+	if err := waitForCanaryReady(ctx, client, cPod.Name, 5*time.Minute); err != nil {
+		fdLog.Error(err, "canary pod is not ready, delete it.", "pod", cPod.Name)
+		_ = client.DeletePod(ctx, cPod)
+		return err
+	}
+
+	defer func() {
+		fdLog.Info("delete canary pod", "pod", cPod.Name)
+		if err := client.DeletePod(ctx, cPod); err != nil {
```
Comment (zxh326) [inline pkg/fuse/grace.go]: Is there any way to ensure recycle canary pod if delete fails?

File: pkg/fuse/grace.go [hunk 4]
```diff
@@ -0,0 +1,364 @@
...
+
+	_, err = conn.Write([]byte(message))
+	if err != nil {
+		fdLog.Error(err, "error sending message")
+		return err
+	}
+
+	fdLog.Info("trigger gracefully shutdown successfully", "name", name)
+	return nil
+}
```
Comment (zxh326) [inline pkg/fuse/grace.go:364]: directly execute the upgrade operation? why we need a socket?

File: dashboard-ui-v2/src/components/pod-basic.tsx [hunk 5]
```diff
@@ -41,11 +45,36 @@ const PodBasic: React.FC<{
...
+      true,
+    )
+    message.success('Successfully trigger pod smoothly upgrade')
+  }
+
   return (
     <ProCard
       title={<FormattedMessage id="basic" />}
       extra={
         <>
```
Comment (zxh326) [inline dashboard-ui-v2/src/components/pod-basic.tsx]: add a [Space Tag](https://ant.design/components/space) avoid components clinging together

File: pkg/config/setting.go [hunk 6]
```diff
@@ -522,13 +521,12 @@ func GenPodAttrWithMountPod(ctx context.Context, client *k8sclient.K8sClient, mo
 	}
 	attr.Resources = resources
 	setting := &JfsSetting{
-		IsCe:      IsCEMountPod(mountPod),
-		PV:        pv,
-		PVC:       pvc,
-		Name:      mountPod.Annotations[JuiceFSUUID],
-		VolumeId:  mountPod.Annotations[UniqueId],
-		MountPath: filepath.Join(PodMountBase, pvName) + mountPod.Name[len(mountPod.Name)-7:],
```
Comment (zxh326) [inline pkg/config/setting.go:531]: we need this to parse config template

File: pkg/juicefs/mount/pod_mount.go [hunk 7]
```diff
@@ -433,6 +439,17 @@ func (p *PodMount) waitUtilMountReady(ctx context.Context, jfsSetting *jfsConfig
 	if err == nil {
 		return nil
 	}
+	if util.SupportFusePass(jfsSetting.Attr.Image) {
+		logger.Error(err, "pod is not ready within 60s")
+		// mount pod hang probably, close fd and delete it
+		logger.Info("close fd and delete pod")
```
Comment (zxh326) [inline pkg/juicefs/mount/pod_mount.go]: Where to delete pod

File: pkg/fuse/grace.go (hunk 1 above)
Comment (zwwhdls) [reply pkg/fuse/grace.go]: the whole tmp directory will be cleaned up when the pod deleted.

Comment (zwwhdls) [reply pkg/fuse/grace.go]: The tmp directories in each pod are isolated from each other. So I think there is no necessary to make the binary file name to unique.

Comment (zxh326) [reply pkg/fuse/grace.go]: if two different versions（ce or ee） of a mount pod are updated in the same node at the same time?

File: pkg/config/setting.go (hunk 6 above)
Comment (zwwhdls) [reply pkg/config/setting.go:530]: the method of get mount pod is in util/resource, and it will be circular refered here. will raise another pr to fix it.

File: pkg/fuse/grace.go (hunk 1 above)
Comment (zwwhdls) [reply pkg/fuse/grace.go]: There is only one version of mount pod, ce or ee. If the same mount pod is updated in the same time, the version will be the same (parsed from configmap).

Comment (zwwhdls) [reply pkg/fuse/grace.go]: I will add a lock of mount pod here.

Comment (zxh326) [reply pkg/fuse/grace.go]: get

File: pkg/fuse/grace.go (hunk 3 above)
Comment (zwwhdls) [reply pkg/fuse/grace.go]: have maked it a job to recycle automatically

File: pkg/fuse/grace/grace.go [hunk 8]
```diff
@@ -0,0 +1,444 @@
...
+	if err != nil {
+		sendMessage(conn, "FAIL get pod")
+		log.Error(err, "get pod error", "name", name)
+		return
+	}
+	if mountPod.Spec.NodeName != config.NodeName {
+		sendMessage(conn, "FAIL pod is not on node")
+		return
+	}
+	ce := util.ContainSubString(mountPod.Spec.Containers[0].Command, "format")
```
Comment (zxh326) [inline pkg/fuse/grace/grace.go]: use metaurl or image?

maybe the user volume name contains `format`?

File: pkg/fuse/grace/grace.go [hunk 9]
```diff
@@ -0,0 +1,444 @@
...
+		case <-ctx.Done():
+			sendMessage(conn, "FAIL Upgrade mount pod timeout")
+			return
+		}
+	}
+}
+
+func (p *podUpgrade) uploadBinary(ctx context.Context) error {
+	ce := util.ContainSubString(p.pod.Spec.Containers[0].Command, "format")
+	if ce {
```
Comment (zxh326) [inline pkg/fuse/grace/grace.go]:
```suggestion
	if p.ce {
```

**Review by zxh326 — APPROVED** [review]
